plugins { id 'com.android.application' }

android {
    namespace 'com.jarves.android'
    compileSdk 36
    defaultConfig {
        applicationId 'com.jarves.android'
        minSdk 26
        targetSdk 36
        versionCode 5
        versionName '0.4.1'
    }
}

dependencies {
    implementation("com.alphacephei:vosk-android:0.3.75@aar")
    implementation("net.java.dev.jna:jna:5.18.1@aar")
}
