plugins { id 'com.android.application' }

android {
    namespace 'com.jarves.android'
    compileSdk 37
    defaultConfig {
        applicationId 'com.jarves.android'
        minSdk 26
        targetSdk 37
        versionCode 4
        versionName '0.4.0'
    }
}

dependencies {
    implementation("com.alphacephei:vosk-android:0.3.75@aar")
    implementation("net.java.dev.jna:jna:5.18.1@aar")
}
